// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOMd69pZh5BNEWWd1dmvtilqGxwiRryFg',
    appId: '1:1092349005213:web:8e997b1e6c3f3284f33374',
    messagingSenderId: '1092349005213',
    projectId: 'crogram-6ab21',
    authDomain: 'crogram-6ab21.firebaseapp.com',
    storageBucket: 'crogram-6ab21.appspot.com',
    measurementId: 'G-EJ2PR70EGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG-X8LioI9p2LHZqrJGy8YIfEJgKTzjnA',
    appId: '1:1092349005213:android:32a521e915d3cc63f33374',
    messagingSenderId: '1092349005213',
    projectId: 'crogram-6ab21',
    storageBucket: 'crogram-6ab21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXopXoOfpXlBGIMlpnL_sEZN_xVADEiXo',
    appId: '1:1092349005213:ios:dccb08a1e18d3c0af33374',
    messagingSenderId: '1092349005213',
    projectId: 'crogram-6ab21',
    storageBucket: 'crogram-6ab21.appspot.com',
    iosClientId: '1092349005213-jltkj1981l1iusbkk38tvij8pamqdc2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );
}
